config/routes.rb
Rails.application.routes.draw do
  root to: "home", to: "home#menu"

  resources :shows, only: [:index, :show]
  resources :lists, only: [:index, :show, :new, :create, :edit, :update, :destroy]
  resources :users, only: [:show, :new, :create, :destroy]

  get "/login", to: "sessions#new", as: "login"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy", as: "logout"

  get "/data", to: "users#data", as: "data"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/list.rb
class List < ApplicationRecord
  has_many :votes
  has_many :users, through: :votes
  has_many :lists_shows
  has_many :shows, through: :lists_shows

  validates :name, uniqueness: true
  validates :name, presence: true
  validates :description, presence: true
  validates :description, length: { minimum: 10 }
end

app/models/lists_show.rb
class ListsShow < ApplicationRecord
  belongs_to :list
  belongs_to :show
end

app/models/show.rb
class Show < ApplicationRecord
  has_many :lists_shows
  has_many :lists, through: :lists_shows
end

app/models/show_list.rb
class ShowList < ApplicationRecord
  belongs_to :list
  belongs_to :show
end

app/models/shows_list.rb
class ShowsList < ApplicationRecord
  belongs_to :list
  belongs_to :show
end

app/models/user.rb
class User < ApplicationRecord
  has_many :votes
  has_many :lists, through: :votes

  has_secure_password
  validates :username, presence: true
  validates :username, uniqueness: true
  validates :password, presence: true
end

app/models/vote.rb
class Vote < ApplicationRecord
  belongs_to :user
  belongs_to :list
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authorized, only: [:show, :index, :edit, :update, :destroy]
  helper_method :current_user, :logged_in?
  #  Creates the session assigned to the user's id
  def login_user(user)
    session[:user_id] = @user.id
  end

  # defines that the user exists - helper
  def current_user
    if session[:user_id]
      User.find(session[:user_id])
    else
      nil
    end
  end

  # Boolean to identify that the user value is strict boolean
  def logged_in?
    !!current_user
  end

  # used to allow specific routes avaliable to user
  def authorized
    unless logged_in?
      flash[:notice] = "Please Log In"
      redirect_to login_path
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  # root menu - splash page
  def menu
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
  end

  # Create new user does not automatically login
  # Some Lists are not associated specific users due to previous seed
  def show
    @list = List.find(params[:id])
  end

  def new
    @list = List.new
  end

  def create
    @list = List.create(list_params)
    @user = User.find(session[:user_id])
    byebug
    if @list.valid?
      @user.lists << @list
      redirect_to @list
    else
      flash[:message] = @list.flash[message].errors.full_messages
      render :new
    end
  end

  def edit
    @list = List.find(params[:id])
  end

  def update
    @list = List.find(params[:id])
    @list.update(list_params)
    redirect_to @list
  end

  def destroy
    @list = List.find(params[:id])
    @list.destroy
    redirect_to lists_path
  end

  private

  def list_params
    params.require(:list).permit(:name, :description, users_ids: [], show_ids: [])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :authorized, only: [:new, :create, :menu, :login]
  # Authenticated to view specific buttons and routes
  # creates new session for the user
  def create
    @user = User.find_by(username: params[:username])

    if @user && @user.authenticate(params[:password])
      session[:user_id] = @user.id
      login_user(@user)
      redirect_to lists_path
    else
      flash[:notice] = "Please Try Again"
      redirect_to login_path
    end
  end

  # Deletes the session
  def destroy
    session.delete(:user_id)
    redirect_to root_path
  end
end

app/controllers/shows_controller.rb
class ShowsController < ApplicationController
  def index
    @shows = Show.all
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :authorized, only: [:new, :create, :menu]

  def show
    @user = User.find(session[:user_id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.create(user_params)
    if @user.valid?
      redirect_to login_path
    else
      flash[:message] = @user.errors.full_messages
      render :new
    end
  end

  # display little data about the web app.
  # Will include logic for top most vidoes selected, etc.
  def data
    @users = User.all
    @shows = Show.all
    @lists = List.all
  end

  private

  def user_params
    params.require(:user).permit(:username, :password, lists_id: [])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/show_lists_helper.rb
module ShowListsHelper
end

app/helpers/shows_helper.rb
module ShowsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/home/menu.html.erb
<h1> Welcome to Have You Seen </h1>
<h3> - the TV/movie list creator - </h3>

<%= button_to "Log In", login_path, method: :get %> <br>
<%= button_to "Create Profile", new_user_path, method: :get %>

app/views/lists/edit.html.erb
<h1>Edit List</h1>
<div>

<%= form_for @list do |f| %>
  <%= f.label :name %><br>
  <%= f.text_field :name %><br>
  <%= f.label :description %><br>
  <%= f.text_area :description %><br>
  <%= f.label :shows %>:<br>
  <%= f.collection_check_boxes :show_ids, Show.all.order(:title), :id, :title do |b| %><br>
    <%= b.check_box(class: "check_box") %>
     <%= b.object.title %><br>
   <% end %>
  <%= f.submit "Update" %>
<% end %>
</div>

app/views/lists/index.html.erb
<h1> All Lists </h1>
<%= button_to "Create List", new_list_path, method: :get %><br>
<%= button_to "View Shows", shows_path, method: :get %><br>
<%= button_to "View My Lists", user_path(session[:user_id]), method: :get %><br>
<%= button_to "Log Out", logout_path, method: :delete %>
    <div>
    <ul> List name:
        <% @lists.each do |list| %>
            <li> <%= link_to list.name, list_path(list) %> - <%= list.description %></li> <br>
        <% end %>
        </ul>
    </div>

app/views/lists/new.html.erb
<h1>New List</h1>
<div>

<%= form_for @list do |f| %>
  <%= f.label :name %><br>
  <%= f.text_field :name %><br>
  <%= f.label :description %><br>
  <%= f.text_area :description %><br>
  <%= f.label :shows %>:<br>
  <%= f.collection_check_boxes :show_ids, Show.all.order(:title), :id, :title do |b| %><br>
    <%= b.check_box(class: "check_box") %>
     <%= b.object.title %><br>
   <% end %>
  <%= f.submit "Submit" %>
<% end %>
</div>

app/views/lists/show.html.erb
<%= button_to "All Lists", lists_path, method: :get %><br>

<% @list.users.each do |user| %>
    <% if user == current_user %>
<%= button_to "Edit List", edit_list_path(@list), method: :get %><br>
<%= button_to "Delete List", @list, method: :delete %>
    <% end %>
<% end %>

<h1>List: <%= @list.name %> </h1>

<h2> Description: <%= @list.description %> </h2>
    <ol> Shows:
    <% @list.shows.each do |show| %>
        <div><li><%= show.title %></div>
    <% end %>
    </ol>

app/views/shows/index.html.erb
<h1> All Shows</h1>
<%= button_to "View All Lists", lists_path, method: :get %>
<ul>
    <% @shows.each do |show| %>
        <li><%= show.title %></li>
    <% end %>
</ul>

app/views/users/data.html.erb
<label>Number of current users: <%= @users.count %> </label><br>
<label>Number of current shows: <%= @shows.count %> </label><br>
<label>Number of lists created: <%= @lists.count %> </label>

app/views/users/new.html.erb
<h1>Create User</h1>

<%= form_for @user do |f| %>
  <%= f.label :username %><br>
  <%= f.text_field :username %><br>
  <%= f.label :password %><br>
  <%= f.password_field :password %><br>
  <%= f.submit "Create" %>
<% end %>

app/views/users/show.html.erb
<h1> Hello <%= @user.username %></h1>
<%= button_to "All Lists", lists_path, method: :get %><br>
<%= button_to "Log out", logout_path, method: :delete %>
 <ul>Lists:
    <% @user.lists.each do |list| %>
         <li><%= link_to list.name, list %> - <%= list.description %></li><br>
    <% end %>
    </ul>